language: objective-c
osx_image: xcode7.3
sudo: false
script:
  - set -o pipefail && xcodebuild build test -project WordPressCom-Analytics-iOS.xcodeproj -scheme WordPressComAnalytics -sdk iphonesimulator | xcpretty -c
